version: "3.5"
services:
  nats:
    image: nats:2.1.8
    ports:
      - "8222:8222"
      - "4222:4222"
    container_name: nats
    networks: ["nats"]
  nats-1:
    image: nats:2.1.8
    container_name: nats-1
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats:2.1.8
    container_name: nats-2
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats